pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    env.GOCACHE = '/var/jenkins_home/workspace/test/.cache'
                    sh 'go test -v ./...'
                }
            }
        }
    }
}
