# fly.toml app configuration file generated for bugtracker-frontend-young on 2025-10-17T13:39:24-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bugtracker-frontend-young'
primary_region = 'sjc'

[build]
  NEXT_PUBLIC_API_URL="https://bugtracker-backend-young.fly.dev"
  
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
