name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  unit-tests-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache-dependency-path: |
            bugtracker-backend/go.sum

      - name: Execute Backend Unit tests
        working-directory: ./bugtracker-backend
        run: |
          go test -v ./...